alias: "Notification: devoirs a faire"
description: Pronote notif devoirs à faire
triggers:
  - at: "17:30:00"
    trigger: time
conditions:
  - condition: state
    entity_id: calendar.vacances_enfants
    for:
      hours: 0
      minutes: 0
      seconds: 0
    state: "off"
actions:
  - data:
      title: Pronote
      message: >-
        {% set items =
         state_attr('sensor.pronote_NOM PRENOM_homework','homework') %} {% for
         item in items if item.date > now().date() and item.date <= (now().date()
         + timedelta(days=4)) and item.date.weekday() not in [5, 6] %}
        {{ item.date.strftime("%d/%m") }} {{ item.subject }} {{ item.description
        }}       
         {% for file in item.files %}
         {{ file.name }}
         {% if file.url %}
             [ ]({{ file.url }})
           {% endif %}{% endfor %}{% endfor %}
    action: notify.telegram
mode: single
